import { ArrowUpRight, GitBranch, Mail, MapPin } from 'lucide-react'

const projects = [
 {title:'Client Websites — Cape Town Hospitality (OREN)', year:'2026', tags:['Next.js','React'], desc:'Delivered 3 production restaurant websites for Cape Town clients with custom booking and menu experiences.', image:'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-QRl5vCrkLX43478FGZWOzB2tTl59aJ.png', live:'https://dev-oren.lovable.app', repo:'#'},
 {title:'Portfolio Website', year:'2026', tags:['Next.js','React','Design'], desc:'A responsive personal portfolio that turns engineering work, product thinking, and visual craft into one clear story.', image:'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-iq31IJVUK2lOJN4uM3EmZIlkvQOhxQ.png', live:'#', repo:'https://github.com/Ansh-vibe/Ansh-s-responsive-Portfolio-Website'},
 {title:'Hospitality Landing Experience', year:'2026', tags:['React','UX'], desc:'Editorial restaurant interface concept with immersive imagery, reservation-first navigation, and expressive typography.', image:'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-tCgOMDzVnBU7C8KOdP9vmicGM8T9Tq.png', live:'#', repo:'#'},
 {title:'Restaurant Web Platform', year:'2026', tags:['Next.js','Frontend'], desc:'A conversion-focused dining experience designed around menus, reviews, location, and online ordering.', image:'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-vQyC9ZroJOZPoUQkyodpr6YeJcKzDF.png', live:'#', repo:'#'},
]
const stack = ['React','Next.js','TypeScript','JavaScript ES6+','Python','C++','HTML5','CSS3','Tailwind CSS','REST APIs','MongoDB','Git','GitHub','Vercel','AWS Foundations']

function ProjectCard({p}:{p:typeof projects[number]}) { return <article className="project-card"><img className="project-image" src={p.image} alt={`${p.title} project preview`} /><div style={{padding:24}}><div style={{display:'flex',justifyContent:'space-between',gap:12,marginBottom:22}}><span className="eyebrow">{p.year}</span><span className="mono muted">{p.tags.join(' · ')}</span></div><h3 style={{fontSize:'clamp(1.5rem,3vw,2.2rem)',lineHeight:1,letterSpacing:'-.05em',margin:'0 0 14px'}}>{p.title}</h3><p className="muted" style={{lineHeight:1.6,margin:'0 0 24px'}}>{p.desc}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a className="button" href={p.live} target="_blank">Live site <ArrowUpRight size={16}/></a><a className="button alt" href={p.repo} target="_blank"><GitBranch size={16}/> GitHub</a></div></div></article> }

export default function Home(){return <main>
 <nav className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'25px 0'}}><a href="#top" className="mono">AV<span style={{color:'var(--accent)'}}>.</span></a><div style={{display:'flex',gap:24}} className="mono"><a href="#about">About</a><a href="#work">Work</a><a href="#contact">Contact</a></div></nav>
 <section id="top" className="container" style={{padding:'82px 0 130px'}}><div className="eyebrow">status: open to opportunities / role: full-stack developer / base: Kanpur, IN</div><div style={{marginTop:72}}><h1 className="display">HI, I’M<br/><span style={{color:'var(--accent)'}}>ANSH.</span></h1><div style={{display:'flex',justifyContent:'space-between',gap:32,alignItems:'end',marginTop:36,flexWrap:'wrap'}}><p style={{fontSize:'clamp(1.2rem,2.5vw,2rem)',maxWidth:540,lineHeight:1.25,margin:0}}>A full-stack developer driven by crafting striking and unforgettable web applications.</p><div style={{display:'flex',gap:12}}><a className="button" href="#work">View selected work <ArrowUpRight size={16}/></a><a className="button alt" href="#contact">Get in touch</a></div></div></div></section>
 <section id="about" className="section"><div className="container"><div className="section-heading"><span className="eyebrow">01 / About me</span><h2 className="section-title">I turn ideas into <span style={{color:'var(--accent)'}}>useful</span> digital experiences.</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:64}}><p style={{fontSize:'1.3rem',lineHeight:1.45,margin:0}}>I’m Ansh Vishwakarma, a full-stack developer and founder who builds production-ready web platforms with a sharp eye for interaction, performance, and detail.</p><div className="muted" style={{lineHeight:1.7}}><p style={{marginTop:0}}>From AI-powered tools to hospitality client sites, I enjoy working across the stack and making complex products feel simple. I’m currently seeking a software engineering role where I can build scalable products with a collaborative team.</p><p className="mono">Based in Kanpur · working worldwide</p></div></div></div></section>
 <section id="work" className="section"><div className="container"><div className="section-heading"><span className="eyebrow">02 / My work</span><h2 className="section-title">Selected <span style={{color:'var(--accent)'}}>projects.</span></h2></div><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))'}}>{projects.map((p)=><ProjectCard key={p.title} p={p}/>)}</div></div></section>
 <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">03 / Experience</span><h2 className="section-title">Building with <span style={{color:'var(--accent)'}}>intent.</span></h2></div><div style={{borderTop:'1px solid var(--line)'}}><div style={{display:'grid',gridTemplateColumns:'1fr 3fr',gap:30,padding:'28px 0',borderBottom:'1px solid var(--line)'}}><span className="mono">2025 — now</span><div><h3 style={{margin:'0 0 8px',fontSize:'1.6rem'}}>Founder / Full-Stack Developer</h3><p className="muted" style={{margin:0,lineHeight:1.6}}>Independent product development across AI tools, client platforms, and responsive web experiences.</p></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 3fr',gap:30,padding:'28px 0',borderBottom:'1px solid var(--line)'}}><span className="mono">2026</span><div><h3 style={{margin:'0 0 8px',fontSize:'1.6rem'}}>Client Websites — Cape Town Hospitality</h3><p className="muted" style={{margin:0,lineHeight:1.6}}>Delivered three production restaurant websites with booking, menu, gallery, reviews, and contact experiences.</p></div></div></div></div></section>
 <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">04 / Education + training</span><h2 className="section-title">Always <span style={{color:'var(--accent)'}}>learning.</span></h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:20}}><div className="project-card" style={{padding:26}}><span className="eyebrow">Education</span><h3 style={{fontSize:'1.7rem',margin:'24px 0 8px'}}>Computer Science & Engineering</h3><p className="muted" style={{lineHeight:1.6}}>Foundations in software engineering, problem solving, data structures, and systems thinking.</p></div><div className="project-card" style={{padding:26}}><span className="eyebrow">Training / certifications</span><h3 style={{fontSize:'1.7rem',margin:'24px 0 8px'}}>Modern web development</h3><p className="muted" style={{lineHeight:1.6}}>Continuous hands-on learning across React, Next.js, Python, cloud fundamentals, and product delivery.</p></div></div></div></section>
 <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">05 / Tech stack</span><h2 className="section-title">Tools I use to <span style={{color:'var(--accent)'}}>ship.</span></h2></div><div style={{display:'flex',flexWrap:'wrap',gap:10}}>{stack.map(s=><span className="pill" key={s}>{s}</span>)}</div></div></section>
 <section id="contact" className="section" style={{background:'var(--ink)',color:'var(--white)',borderColor:'var(--ink)'}}><div className="container"><span className="eyebrow">06 / Contact</span><h2 className="section-title" style={{marginTop:44}}>Have a good idea?<br/><span style={{color:'var(--accent)'}}>Let’s make it real.</span></h2><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:30,flexWrap:'wrap',marginTop:70}}><div style={{display:'flex',flexDirection:'column',gap:18}}><a href="mailto:contact.ansh03@gmail.com" className="mono"><Mail size={16} style={{verticalAlign:'middle',marginRight:10}}/>contact.ansh03@gmail.com</a><span className="mono"><MapPin size={16} style={{verticalAlign:'middle',marginRight:10}}/>Kanpur, India</span></div><div style={{display:'flex',gap:12}}><a className="button" style={{background:'var(--accent)',color:'var(--ink)'}} href="mailto:contact.ansh03@gmail.com">Start a conversation <ArrowUpRight size={16}/></a><a className="button alt" style={{borderColor:'var(--white)',color:'var(--white)'}} href="https://github.com/Ansh-vibe" target="_blank"><GitBranch size={16}/> GitHub</a></div></div></div></section>
 <footer className="container" style={{display:'flex',justifyContent:'space-between',padding:'24px 0',gap:20,flexWrap:'wrap'}}><span className="mono">© 2026 Ansh Vishwakarma</span><span className="mono">build: passing · made with intent</span><a className="mono" href="#top">back to top ↑</a></footer>
 </main>}
